In [ ]:

!pip install pandas requests plotly nbformat

Requirement already satisfied: pandas in c:\users\divya\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: requests in c:\users\divya\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: plotly in c:\users\divya\anaconda3\lib\site-packages (5.24.1)
Requirement already satisfied: nbformat in c:\users\divya\anaconda3\lib\site-packages (5.10.4)
Requirement already satisfied: numpy>=1.26.0 in c:\users\divya\anaconda3\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\divya\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\divya\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\divya\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\divya\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\divya\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\divya\anaconda3\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\divya\anaconda3\lib\site-packages (from requests) (2025.8.3)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\divya\anaconda3\lib\site-packages (from plotly) (9.0.0)
Requirement already satisfied: packaging in c:\users\divya\anaconda3\lib\site-packages (from plotly) (24.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\divya\anaconda3\lib\site-packages (from nbformat) (2.20.0)
Requirement already satisfied: jsonschema>=2.6 in c:\users\divya\anaconda3\lib\site-packages (from nbformat) (4.23.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\divya\anaconda3\lib\site-packages (from nbformat) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\divya\anaconda3\lib\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\divya\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\divya\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\divya\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\divya\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (0.22.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\divya\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\divya\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (308)
Requirement already satisfied: six>=1.5 in c:\users\divya\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import requests
import plotly.express as px
import json

In [3]:
def fetch_data():
    url = "https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all"
    try:
        r = requests.get(url)
        r.raise_for_status() # for api working 
        data = r.json()
        #nested json into flat table
        df = pd.json_normalize(data)
        #Cleaning column names by removing the 'nutritions.' prefix
        df.columns = [c.replace("nutritions.","") for c in df.columns]
        return df
    except Exception as e:
        print(f"Error fetching data {e}")
        return None
    
df = fetch_data()
df.head()

,name,id,family,order,genus,calories,fat,sugar,carbohydrates,protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.0,18.0,18.0,0.0
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.4,5.4,5.5,0.8
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.2,2.6,3.9,0.9
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.1,10.0,15.0,0.4

In [4]:
print(f"Total fruit analyzed {len(df)}")
print("\n--- Nutritional Summary ---")
display(df.describe())

Total fruit analyzed 49

--- Nutritional Summary ---

               id    calories        fat      sugar  carbohydrates    protein
count   49.000000   49.000000  49.000000  49.000000      49.000000  49.000000
mean    58.816327   68.510204   2.005102   7.990408      12.152857   1.368163
std     32.734840   86.454256   8.872052   4.907164       5.661771   2.367021
min      1.000000   15.000000   0.000000   0.000000       3.100000   0.000000
25%     33.000000   39.000000   0.200000   4.300000       8.300000   0.540000
50%     68.000000   50.000000   0.300000   8.000000      11.300000   0.900000
75%     84.000000   70.000000   0.500000  10.000000      17.000000   1.200000
max    104.000000  628.000000  61.000000  19.100000      27.100000  15.000000